version: '3.7'

services:
 spark-master:
   image: bitnami/spark:latest
   command: bin/spark-class org.apache.spark.deploy.master.Master
   hostname: spark-master
   user: root
#   container_name: spark-master
   environment:
     SPARK_NO_DAEMONIZE: "true"
   volumes:
     - ~/rp/git/Spark-Playground:/tmp/Spark-Playground
   networks:
     - spark-net
   ports:
    - "9090:8080"
    - "7077:7077"
 spark-worker-1:
   image: bitnami/spark:latest
   command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
   hostname: spark-worker-1
   user: root
   container_name: spark-worker-1
   depends_on:
     - spark-master
   environment:
     SPARK_MODE: worker
     SPARK_WORKER_CORES: 4
     SPARK_WORKER_MEMORY: 4g
     SPARK_MASTER_URL: spark://spark-master:7077
   volumes:
     - ~/rp/git/Spark-Playground:/tmp/Spark-Playground
   networks:
     - spark-net
 spark-worker-2:
   image: bitnami/spark:latest
   command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
   hostname: spark-worker-2
   user: root
   container_name: spark-worker-2
   depends_on:
     - spark-master
   environment:
     SPARK_MODE: worker
     SPARK_WORKER_CORES: 4
     SPARK_WORKER_MEMORY: 4g
     SPARK_MASTER_URL: spark://spark-master:7077
   volumes:
     - ~/rp/git/Spark-Playground:/tmp/Spark-Playground
   networks:
     - spark-net

networks:
  spark-net:
    driver: bridge

# Spark UI: http://localhost:9090/
# Spark Master: spark://172.19.0.2:7077